name: run example code
on:
 push:
    branches: [ experimental ]

jobs:
  run_example:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18 and python 3.10
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: compile and run example
        run: mvn clean install exec:java