name: run example code
on:
 push:
    branches: [ experimental ]

jobs:
  run_example:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: compile and run example
        run: mvn clean install exec:java